baseURL = "https://www.davidedmiston.com/"
languageCode = "en-us"
theme = "base16"
title = "Globally Scoped"

pygmentsCodefences = true
pygmentsStyle = "pygments"

[permalinks]
  post = "post/:year/:month/:slug"

[markup]
  [markup.highlight]
    codeFences = true
    style = "dracula"

[params]
  project_name = "Globally Scoped"
  project_tagline = "A Technology Blog"
  dateFormat = "2006-01-02"
  paginate = 10
