baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde-hyde"

[params]
  highlightjs = true
  themeColor = "theme-base-0e"
  layoutReverse = true

[params.social]
  twitter = "edmistond"
  github = "edmistond"
  gravatar = "edmistond@gmail.com"
